{% set name = "slcwindinversion" %}
{% set version = "2023.10.post3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/slcwindinversion-{{ version }}.tar.gz
  sha256: 23072dc836de5ddfe77bf875345af0bb04d896c8ee7aa6380bbba2ccea3e9dc7

build:
  entry_points:
    - slcwindinversion = slcwindinversion.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - scipy
    - xsarsea
    - xarray
    - xarray-datatree
    - importlib_resources
    - tqdm

test:
  imports:
    - slcwindinversion
  commands:
    - pip check
    - slcwindinversion --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Python library to generate Level-2A wind speed products from intermediate Sentinel-1 TOPS SLC-derived products.
  license: MIT
  license_file: LICENSE
  home: https://github.com/umr-lops/slcwindinversion

extra:
  recipe-maintainers:
    - agrouaze
